# permissions for end users to view frodobaggins.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: frodobaggins-viewer-role
rules:
- apiGroups:
  - hobbit.lotr.com
  resources:
  - frodobaggins
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - hobbit.lotr.com
  resources:
  - frodobaggins/status
  verbs:
  - get
