
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - hobbit.lotr.com
  resources:
  - frodobaggins
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - hobbit.lotr.com
  resources:
  - frodobaggins/finalizers
  verbs:
  - update
- apiGroups:
  - hobbit.lotr.com
  resources:
  - frodobaggins/status
  verbs:
  - get
  - patch
  - update
